// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxygevbgpmlelfwrmutw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4eWdldmJncG1sZWxmd3JtdXR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4ODgzNjQsImV4cCI6MjA2NTQ2NDM2NH0.I6WgmwGMxP-Gv6D72JRVk0rN8C1e31vGsTVGomfFCDM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);